on:
  release:
    types: [published]

name: publish-to-npmjs

env:
  PNPM_VERSION: "6.19.1"
  NODE_VERSION: "14.17.3"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Setup PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: "${{ env.PNPM_VERSION }}"
      - uses: actions/setup-node@v2
        with:
          cache: pnpm
          node-version: "${{ env.NODE_VERSION }}"
      - name: Publish single module
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

        # the `echo` below deliberately uses single quotes so that the
        # token isn’t written to the file; instead, npm should replace
        # it at runtime.

        run: |
          package=`echo "${{ github.event.release.name }}" | cut -d ' ' -f 1`

          echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc

          cd packages/$package
          pnpm install --frozen-lockfile --filter "$package..."
          pnpm run build --filter "$package"
          pnpm publish --no-git-checks --filter "$package"
      - name: Generate docs for all packages
        # TODO this means updating all docs for all changes, not just
        # the current module, regardless of release status; see
        # TypeStrong/typedoc#1791
        run: |
          pnpm install -r --frozen-lockfile
          pnpm typedoc
      - name: Deploy docs for all packages to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
