name: Run tests

on:
  push:
    branches-ignore:
      - main

env:
  PNPM_VERSION: "6.19.1"
  NODE_VERSION: "14.17.3"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Setup PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: "${{ env.PNPM_VERSION }}"
      - uses: actions/setup-node@v2
        with:
          cache: pnpm
          node-version: "${{ env.NODE_VERSION }}"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run tests
        run: pnpm test

      # TODO add coverage using
      # <https://github.com/marketplace/actions/code-coverage-summary>
      # once nyc works again
  check-build-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: "${{ env.PNPM_VERSION }}"
      - uses: actions/setup-node@v2
        with:
          cache: pnpm
          node-version: "${{ env.NODE_VERSION }}"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run build
        run: pnpm run build
  check-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: "${{ env.PNPM_VERSION }}"
      - uses: actions/setup-node@v2
        with:
          cache: pnpm
          node-version: "${{ env.NODE_VERSION }}"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Generate docs for all packages
        run: pnpm typedoc
